okfde/froide

- .gitignore
- Makefile
- froide/foirequest/forms.py
- froide/foirequest/tests/test_request.py
- froide/settings.py
- froide/urls.py
- requirements-test.txt
> Use Whoosh instead of elasticsearch for tests; reducing dependencies for local testing

- froide/foirequest/delivery.py
in yearless logfiles, log parsing breaks on Feb 29. This should fix it
> fix leap year

- froide/team/templates/team/team_detail.html
- locale/de/LC_MESSAGES/django.po
This might be enough to fix the issue reported in #500
> Improve team page style & use gender neutral terms for team roles

- froide/foirequest/forms/__init__.py
- froide/foirequest/forms/project.py
- froide/foirequest/models/project.py
- froide/foirequest/templates/foirequest/_assign_project_form.html
- froide/foirequest/templates/foirequest/body/settings.html
- froide/foirequest/templatetags/foirequest_tags.py
- froide/foirequest/urls/request_urls.py
- froide/foirequest/views/__init__.py
- froide/foirequest/views/request_actions.py
- locale/de/LC_MESSAGES/django.po
**Note**: This contains a lot of similar code to the 'Add team to project' feature.
> ✨ Add setting to change project of a request

- froide/foirequest/feeds.py
> ✨ Ignore unknown events in request feed

- froide/foirequest/views/attachment.py
- frontend/javascript/components/redaction/confirm-no-redaction.vue
- frontend/javascript/components/redaction/redaction.vue
- locale/de/LC_MESSAGES/django.po
I'm not sure about the wording of the modal, please also have a look at that when reviewing.
Closes #522
> 🚸 Show confirmation modal if user click "no redaction needed" after redacting

- froide/foirequest/views/make_request.py
- froide/settings.py
- frontend/javascript/components/makerequest/request-form.vue
> ✨ Show warning for non meaningful subjects

- froide/document/admin.py
Allows collection documents to be moved to a directory.
> add admin action to move docs into directory

- froide/document/auth.py
This PR touches on permissions, please review with care
> 🛂 allow team members to view private documents

- froide/account/forms.py
- froide/account/templates/account/widgets/image.html
- froide/helper/fields.py
- froide/helper/templates/helper/forms/widgets/image.html
- froide/helper/widgets.py
- froide/organization/forms.py
- froide/organization/models.py
- froide/organization/services.py
- froide/organization/templates/organization/emails/organization_invite.txt
- froide/organization/templates/organization/organization_detail.html
- froide/organization/templates/organization/organization_list.html
- froide/organization/templates/organization/organization_update_form.html
- froide/organization/urls.py
- froide/organization/views.py
- froide/urls.py
- frontend/styles/components/misc.scss
Organization pages show the logo, name and description of organization as well as a list of its members (if their profile is public) with their name and profile description.
> ✨ Add organization pages

- Makefile
- froide/accesstoken/tests.py
- froide/account/tests/test_account.py
- froide/conftest.py
- pytest.ini
- requirements-test.in
- requirements-test.txt
I added the following libraries:
- [pytest](https://docs.pytest.org/en/7.1.x/contents.html)
- [pytest-django](https://pytest-django.readthedocs.io/en/latest/#)
- [pytest-factoryboy](https://pytest-factoryboy.readthedocs.io/en/stable/#)
Factories and fixtures can be registered in conftest.py and then be used in all tests without imports
As an example I changed the tests in accesstoken account/test/test_account.py to pytest-tests
> Mn add pytest

- froide/foirequest/templatetags/foirequest_tags.py
- froide/foirequest/tests/test_misc.py
- frontend/javascript/request.ts
- frontend/styles/components/request/message.scss
This is an alternative solution to #610
> 💄 Truncate links in css instead of message rendering

- froide/helper/redaction.py
To be merged after https://github.com/okfde/django-filingcabinet/pull/29
> 👽️ Use changed get_images_from_pdf api

- froide/organization/templates/organization/organization_detail.html
- froide/organization/templates/organization/organization_list.html
- frontend/styles/components/misc.scss
- 💄 move `.partner-logo` class to froide
- 💄 move image classes to froide
- 💄 refine organization pages
> organization updates

- froide/foirequest/forms/request.py
- froide/foirequest/templates/foirequest/_assign_project_form.html
- froide/foirequest/templates/foirequest/body/settings.html
- froide/team/forms.py
- froide/team/templates/team/_assign_team_form.html
- 💄 use same headline level across settings
- 💄 card layout for foirequest settings ui
- 💬 update translations
- 🩹 keep project's team and request's team in sync:
modifying a project's team will now update all corresponding requests to keep permissions in line
> update foirequest settings

- froide/accesstoken/admin.py
- froide/account/admin.py
- froide/bounce/admin.py
- froide/campaign/admin.py
- froide/comments/admin.py
- froide/document/admin.py
- froide/foirequest/admin.py
- froide/frontpage/admin.py
- froide/georegion/admin.py
- froide/guide/admin.py
- froide/helper/middleware.py
- froide/helper/templatetags/content_helper.py
- froide/helper/utils.py
- froide/letter/admin.py
- froide/organization/admin.py
- froide/problem/admin.py
- froide/publicbody/admin.py
- froide/team/admin.py
- froide/upload/admin.py
- froide/upload/api_views.py
> Add some Django code upgrades

- froide/helper/templates/helper/forms/widgets/tag_autocomplete.html
- froide/helper/templatetags/frontendbuild.py
- froide/helper/tests/test_frontendbuild.py
- froide/helper/widgets.py
- froide/publicbody/widgets.py
- froide/templates/admin/base_site.html
- froide/upload/forms.py
> Use JSModulePath in widget media to support type module scripts

- froide/foirequest/models/message.py
- froide/foirequest/models/request.py
- froide/foirequest/tests/test_request.py
- froide/foirequest/utils.py
- froide/settings.py
- locale/de/LC_MESSAGES/django.po
> Add link to explanation to throttle error message

- froide/account/__init__.py
- froide/account/admin.py
- froide/account/forms.py
- froide/account/registries.py
- froide/account/services.py
- froide/account/tasks.py
- froide/account/templates/admin/account/user/change_form.html
- froide/account/utils.py
- froide/account/views.py
- froide/bounce/models.py
- froide/bounce/utils.py
- froide/foirequest/apps.py
- froide/foirequest/services.py
- froide/foirequest/tests/test_request.py
- froide/follow/forms.py
- froide/helper/tasks.py
- froide/publicbody/admin.py
- froide/team/__init__.py
- froide/team/forms.py
- setup.py
- Making `foirequest`, `account`, `publicbody` more stand-alone.
> Decouple apps from each other

- froide/publicbody/templates/publicbody/jurisdiction.html
> 🐛 Fix public body url in jurisdiction page

- froide/helper/templatetags/search_helper.py
> 🐛 handle pages without request context

- froide/foirequest/templates/foirequest/_request_search.html
- froide/helper/templates/helper/search/search_base.html
- frontend/javascript/snippets/search.ts
was deleted accidentally in a63f8be, brought back as a simpler utility
> 🩹 fix select auto-submit on request search

- froide/foirequest/utils.py
Old formats contained plus sign, new contain only dots.
> Fix anonymization of old secret address formats

- froide/foirequest/templates/foirequest/sent.html
- froide/templates/snippets/share_buttons.html
- **✨ use new share buttons on request sent page**
- **🩹 hide modal after sharing on mastodon**
> share links on foirequest sent page

- froide/settings.py
Kombu needs this to process mail queues.
> Added 'application/json' to celery_accept_content

- froide/settings.py
See https://pyauth.github.io/pyotp/#pyotp.totp.TOTP.verify
Closes #823
> Set MFA TOTP valid window to one before and after

- froide/account/services.py
- froide/account/tests/test_account.py
> 🐛 Redact names with spaces if split in attachment name

- MANIFEST.in
- pyproject.toml
- **🍱 add static files to package**
- **📌 keep channels at v3**
> tooling fixes

- froide/foirequest/api_views.py
- froide/foirequest/forms/message.py
- froide/foirequest/tests/test_api.py
- froide/foirequest/views/message.py
- froide/settings.py
- froide/upload/api_views.py
- froide/upload/models.py
For use with OAuth by providing message ID and Upload URL.
> Add attachment upload API

- froide/foirequest/models/request.py
- froide/foirequest/templates/foirequest/body/timeline.html
> 🐛 Request page: Use local time for timeline key calculation

- froide/foirequest/filters.py
- froide/helper/auth.py
- froide/helper/search/filters.py
- froide/helper/templates/helper/forms/bootstrap_field.html
required for https://github.com/okfde/fragdenstaat_de/pull/601
> staff auth decorator, form labels

- froide/foirequest/views/request.py
- frontend/javascript/request.ts
- package.json
- pnpm-lock.yaml
- **⬆️ upgrade driver.js, slightly improves accessibility for tours on request page**
- **♻️ mildly improve request.ts**
> ⬆️ ugprade driver.js

- froide/foirequest/tasks.py
- froide/helper/email_parsing.py
> Add date header field parsing fix

- froide/foirequest/tasks.py
- froide/foirequest/templates/foirequest/redact.html
- froide/foirequest/templates/foirequest/upload_postal_message_new.html
- froide/foirequest/views/attachment.py
- froide/foirequest/views/message.py
- froide/locale/de/LC_MESSAGES/django.po
- froide/templates/base.html
- froide/templates/fullscreen_app.html
- frontend/javascript/components/docupload/document-uploader.vue
- frontend/javascript/components/docupload/file-document.vue
- frontend/javascript/components/postupload/post-upload.vue
- frontend/javascript/components/redaction/pdf-redaction.vue
- frontend/javascript/components/upload/file-uploader.vue
- frontend/javascript/postupload.js
- frontend/styles/components/base.scss
- frontend/styles/maps.scss
fcf2fdb855d94ac60a35b02eea83669d3b8168b7 is the meat here
> postupload fixes

- froide/foirequest/tasks.py
> fix redact task KeyError

- froide/foirequest/views/message.py
- frontend/javascript/components/docupload/document-uploader.vue
- frontend/javascript/components/postupload/post-upload.vue
- the jurisdiction/classifiction key typo you found
- step 1/3 non bold issue
- i realized that i could upload docx, odt
> postupload more small fixes

- froide/foirequest/api_views.py
- **🐛 Fix typo serializing subject in content field**
- **⚡️ Prefetch attachment infos in FoiMessageSerializer**
> Bugfix & Performance FoiMessageSerialize

- froide/foirequest/models/request.py
- froide/foirequest/templates/foirequest/header/info-box.html
- froide/foirequest/views/request_actions.py
Takes the easy part from https://github.com/okfde/froide/pull/865 to get it merged sooner
> 🚸 Always allow mods to change request status

- .github/workflows/ci.yml
- package.json
- pyproject.toml
- requirements-test.txt
- requirements.txt
- **📌 pin pnpm version in package.json**
- **👷  bump node to 22**
- **👷 drop python 3.10, add python 3.13**
> pin pnpm, bump node + python

- frontend/javascript/components/makerequest/request-form.vue
> 🚸 Show public body request note in multi request form

- frontend/javascript/components/redaction/pdf-redaction.vue
by assuming a minimum virtual viewport of 1000px width for rasterization
re https://github.com/fragdenstaat/issues/issues/12
> fix pdf redaction low resolution on mobile

- froide/foirequest/forms/message.py
- froide/foirequest/views/message.py
> 🐛 fix edit message form not saving correctly

- froide/georegion/api_views.py
- froide/publicbody/admin.py
- frontend/javascript/components/geomatch/geo-matcher.vue
- search for georegion kind detail
- optionally exclude category when searching matches
- Set category on public body when present
> Improve geo matcher

- froide/helper/admin_utils.py
- froide/helper/tests/test_admin_utils.py
- froide/locale/de/LC_MESSAGES/django.po
See https://github.com/fragdenstaat/issues/issues/18
> Check that user entered pk in make_choose_object_action

- frontend/javascript/components/docupload/lib/attachments.js
> fix exifless edge case

- froide/document/tasks.py
To improve initial import time.
> Move service module import into task function

- froide/accesstoken/apps.py
- froide/account/admin.py
- froide/account/apps.py
- froide/comments/apps.py
- froide/comments/models.py
- froide/document/apps.py
- froide/foirequest/admin.py
- froide/foirequest/apps.py
- froide/foirequest/auth.py
- froide/foirequest/signals.py
- froide/foirequest/templatetags/foirequest_tags.py
- froide/foirequest/utils.py
- froide/helper/form_utils.py
- froide/publicbody/apps.py
- froide/team/apps.py
Reduce imports and don't connect signals unless through `AppConfig`. Introduce `XYZAppNoConfig` variants without signals.
> Some ground work to allow imports without side effects

- frontend/javascript/components/postupload/post-upload.vue
see bug report: <https://forum.okfn.de/t/neue-anhangsverwaltung-post-upload-prozess-feedback/4101/2>
> fix postupload flow stuck at resolution step for resolved foirequests

- frontend/javascript/components/docupload/attachment-icon-preview.vue
cf. 3a585c76eeec2004d7d2ffac741fd5e566f7f944
> postupload preview timing polling, again

- froide/account/admin.py
- Add last login date range filter to user list filters
- Add last_login to list_display
- Allows filtering and viewing users by their last login date
closes fragdenstaat/issues#163
> ✨ Add last login date range filter to user admin
