froide/foirequest/tests/test_web.py, froide/urls.py
Also makes use of django.test.SimpleTestCase.assertRedirects in test.
=> Allow shorturls to end in /. Fixes #164

froide/foirequest/forms.py
This solves #213 by adding the current time to the date of the upload form.
=> Add current time to timestamp of manually uploaded messages

froide/foirequest/templates/foirequest/snippets/sidebar.html
Currently, the download buttons in the sidebar look like this:
In order for it to look better, I added these changes, which stretch the buttons to 100 % width and add a small margin between the two buttons:
But the translations need to be changed as well: "Download request as ZIP-file" is too long. I propose "Download as ZIP-file" and in German "Download als ZIP"; as well as "Download as PDF". Then the strings look more symmetric and still express the same information. But I don't know how to change these translations, so feel free to help.
=> Update download buttons in sidebar.html

frontend/styles/components/alpha/header.scss
This PR fixes the text fade-out on the request page (alpha) for Safari to not fade to gray, but the background color instead. Firefox should be unaffected by this patch and still fades correctly.
=> Fix long request text fade-out

froide/foirequest/management/commands/fetch_foi_mail.py
FOI mail class name changed in 3de57145e7f5c32aa3ab8db9785b2a7cfdcb16ce.
=> Fix class name

froide/guide/utils.py
With Topf Secret, many requests don't get a response at all, like this one: https://fragdenstaat.de/anfrage/kontrollbericht-zu-wolke-berlin/
This change allows us to help users get a response by adding guidance to their messages.
=> allow user messages to receive guidance

frontend/javascript/components/redaction/redaction.vue
Fixes https://github.com/okfde/froide/issues/439 by applying the code [from here](https://jsfiddle.net/tagliala/zvkwmf1L/3/).
Note **this is completely untested**, I'm just doing the code changes to bring that forward, as it is a very annoying thing for me and I personally like this solution. :)
Especially it may need to be checked, whether the used FontAwesome version is up-to-date for this syntax…
=> Switch to better FontAwesome icons for revert redaction

README.md, froide/foirequest/tasks.py, froide/settings.py
At FragDenStaat.at, we're using the language code de-at to allow us to use the German translations while overwriting some messages. This throws off Tesseract / django-filer. I'd like to propose allowing a seperate setting for the tesseract language code.
=> Allow TESSERACT_LANGUAGE to be overridden in settings

froide/foirequest/management/commands/cache_text_redactions.py
Sometimes, especially for longer texts, calculating the redaction markup takes too long. We cache the results, but if the request is killed before the end of the calculation, it is never written to the cache.
This commit adds a management command that pre-calculates the redaction markup for all longer messages.
=> 🩹 Add management command to pre-calculate redaction markup

froide/foirequest/auth.py, froide/foirequest/forms/__init__.py, froide/foirequest/forms/message.py, froide/foirequest/forms/project.py, froide/foirequest/signals.py, froide/foirequest/tasks.py, froide/foirequest/templates/foirequest/foiproject_action.html, froide/foirequest/templates/foirequest/foiproject_detail.html, froide/foirequest/urls/project_urls.py, froide/foirequest/views/__init__.py, froide/foirequest/views/message.py, froide/foirequest/views/project.py, froide/letter/utils.py, frontend/javascript/snippets/misc.ts
Similar to Django admin actions, project actions let you select requests from the project page and apply bulk actions to them. Included in this PR are publishing the request and writing a message in the request.
=> Add project actions to execute on many requests

Makefile, docs/conf.py, froide/bounce/tasks.py, froide/bounce/utils.py, froide/foirequest/delivery.py, froide/foirequest/signals.py, froide/helper/email_log_parsing.py, froide/helper/management/commands/parse_mail_log.py, froide/helper/signals.py, froide/helper/tasks.py, froide/helper/tests/test_email_log_parsing.py, froide/helper/tests/test_misc.py, froide/helper/tests/testdata/maillog_001.txt, froide/helper/tests/testdata/maillog_002.txt, froide/helper/tests/testdata/maillog_003.txt, froide/helper/tests/testdata/maillog_004.txt, requirements-test.txt, requirements.in, requirements.txt
This continues @xenein‌s work in #455 and closes #454 
This adds a new [regex-based postfix log parser](https://github.com/okfde/froide/blob/66ac22f77d9142e1962a99cc0878aa3461c58f59/froide/helper/email_log_parsing.py#L13) which sends a [`froide.helper.signals.email_left_queue`](https://github.com/okfde/froide/blob/66ac22f77d9142e1962a99cc0878aa3461c58f59/froide/helper/email_log_parsing.py#L174) signal for each message which was removed from the postfix queue (mostly because they are delivered), which is then used to [update the message status](https://github.com/okfde/froide/blob/66ac22f77d9142e1962a99cc0878aa3461c58f59/froide/foirequest/signals.py#L464) 
Since the postfix parser is no longer specific to foi messages, I moved the code to `froide.helper`.
=> Add postfix logparsing as a seperate task

froide/foirequest/templates/foirequest/body/message/attachments/item.html
fixes #532 
Not totally sure if this does not break something, e.g. if there are edge cases where there is a link on a linked tile
=> Move link from title to attachment tile

froide/comments/templates/froide_comments/comment.html, froide/foirequest/templatetags/foirequest_tags.py
[🐛 Fix requester badge on comments](https://github.com/okfde/froide/commit/d0a8ff18f25dc7e183f7c2057ad1b70378184e9b) fixes a bug that caused the "Requester"-badge no never be shown.
The second comment closes #539 by not showing the badges if the viewer is not logged in. This also applies to the modator-badge
=> Requester comments

frontend/javascript/components/redaction/redaction.vue
Until hasRedactions checked if there were manual redactions. This lead to
1. The frontend showing the green "no redactions needed" as the only button, even if automatic redactions existed
2. No confirmation (#535) being shown when selecting this button
=> 🐛 Include automatic redactions when counting redactions

froide/publicbody/templates/publicbody/snippets/publicbody_proposals.html
This PR aims to fix #581
It seems that the issue was caused by
1. having multiple `class` attributes on html elements and
2. by an issue where `'` was used instead of `"` to end an html attribute's value
This PR merges the multiple `class` attributes into single ones and replaces the `'` with `"`.
=> Fix public body proposal accepting

froide/static/js/pdf.worker.js.map, frontend/javascript/components/docupload/pdf-preview.vue, frontend/javascript/components/redaction/pdf-redaction.vue
So Django 4.0+ manifest static file storage collectstatic can resolve the source mapping reference, even when the file is not available in frontend build.
=> Add fake PDFjs pdf.worker.js.map file

frontend/javascript/components/publicbodyupload/publicbody-upload.vue, frontend/javascript/components/upload/file-uploader.vue
Form submit handles the upload later, so no done button needed.
=> Remove 'done' button from upload dashboard, allow individual upload file removal

frontend/javascript/snippets/form-ajax.ts
`{el}.Modal` doesn't seem to exist (anymore? maybe it did bs4?)
=> 🐛 fix crash in form modal hiding

froide/account/forms.py, froide/account/models.py, froide/account/utils.py, froide/foirequest/templates/foirequest/body/message/message.html, froide/helper/storage.py, froide/settings.py, requirements-test.txt, requirements.in, requirements.txt, setup.py
- Add profile picture on request page with thumbnailing.
- Add function to make sure files in `HashedFileStorage` are deleted if last reference is gone.
- Properly delete profile photos and their thumbnails when requested.
Needs to be deployed with a `fragdenstaat_de` change that removes `easy_thumbnails` from its additional installed apps.
Similar thing should be handled for organisation logos!
=> Add profile picture to request page + housekeeping

froide/settings.py, froide/urls.py, requirements-test.txt, requirements.in, requirements.txt, setup.py
This commit disabled redoc, because it is not easily possible to deploy a redoc copy that does not load external resources
=> 🚀 Use local swagger ui for drf-spectacular

frontend/javascript/components/docupload/document-uploader.vue, frontend/javascript/components/docupload/image-page.vue, package.json, yarn.lock
This commit improves the handling of uploaded images in the document uploader of the attachment management component (i.e. the thing where you create a document out of uploaded images). It does three things:
1. It replaces the library we use for exif detection in the images. Until now we used exif-js which is no longer maintained and does not work in strict mode
2. It fixes the exif support feature detection
3. We now load the image in the component as a blob and stores it there. Until now the image was loaded by the img-tag in the browser and again by exif-js. However we can serve both from the component.
=> ♻️ Replace exif-js with exifreade; fix exif support detection; cache image

froide/foirequest/templates/foirequest/attachment/show.html
This prevents smartphones where we don't show the iframe from loading the pdf (saving bandwidth) and fixes the file being downloaded on iphones in lockdown mode.
=> 🩹 Lazy load attachment pdf iframe

froide/foirequest/templates/foirequest/attachment/manage.html, froide/foirequest/templates/foirequest/request.html, frontend/javascript/components/docupload/document-uploader.vue, frontend/javascript/components/makerequest/request-page.vue, frontend/javascript/lib/django-slot.vue, frontend/javascript/lib/vue-helper.ts
Before, every slot provided to a vue component via django html was stringified, then parsed again by the DOM. Now, a DOM copy of the `<template>` element is used instead (should improve performance).
To reduce confusion between Vue `<slot>`s and this, I propose to not use Vue syntax:
- Registering a template: `<template data-slot="foo" />` instead of `<template v-slot:foo />`
- Rendering the slot: `<django-slot name="foo" />` instead of `<slot name="foo">`
This also uses provide/inject instead of passing the slots as props, which has the additional benefit that `<django-slot name="foo">` can be used even in **nested components** without passing down the slot.
When using `createAppWithProps`, I suggest we always use the Vue component's name as the identifier:
```js
const els = …
```
=> ♻️ rework slot exchange between django/vue

froide/account/templates/account/includes/breadcrumbs.html, froide/foirequest/templates/foirequest/header/breadcrumb.html, froide/foirequest/views/list_requests.py, froide/helper/templates/helper/search/multi_search.html, froide/helper/templatetags/breadcrumb_helper.py, froide/organization/templates/organization/organization_detail.html, froide/organization/templates/organization/organization_list.html, froide/organization/templates/organization/organization_list_own.html, froide/organization/templates/organization/organization_update_form.html, froide/templates/base.html, froide/templates/header.html, froide/templates/simple_base.html, froide/templates/snippets/breadcrumbs.html, frontend/javascript/snippets/search.ts, frontend/styles/components/breadcrumb.scss, frontend/styles/components/dropdown.scss, frontend/styles/components/misc.scss, frontend/styles/main.scss, frontend/styles/variables.scss, package.json, yarn.lock
breadcrumbs will be migrated later
=> new navigation

froide/account/admin.py, froide/account/models.py
So admins of User subclasses have access to search field.
=> Fix: Always annotate deterministic email on queryset in user admin

locale/de/LC_MESSAGES/django.po
DE translation was ahead of msgid which had not been updated.
=> Manually fix translation

froide/document/feeds.py
Query highlight is already marked safe, but could contain braces that interfere with string interpolation. Interpolating it directly via `format_html` works, because the function respects safe strings.
=> Fix interpolation of query highlight

frontend/styles/components/tagautocomplete.scss
Otherwise it might collide with other choices inputs nearby.
=> Change z-index of choices up only on open

froide/publicbody/forms.py
To discourage people from filling in their proposed change in the reason field instead of the actual fields.
=> Move reason to bottom on public body form

froide/foirequest/models/message.py
Fixes a crash in cache_text_redactions if the message was never opened
=> 🐛 Use FoiMessage.get_content if plaintext_redacted could be none

froide/foirequest/views/make_request.py
Otherwise save_draft would be called which does not handle an invalid form well
=> 🐛 Show error if draft invalid

froide/foirequest/templates/foirequest/header/info-box.html
Similar STRs to https://github.com/okfde/froide/issues/816, but if you enter `0` in that input box and press the button, you get a ~~404~~ 400 error. :upside_down_face:
=> Increase minimum input for deadline input to 1 as 0 leads to 400 error

froide/templates/500.html
Going through frontend requires request which is unavailable on error page
=> Add css/js directly to 500 template

froide/foirequest/feeds.py
Otherwise the public_body is retrieved from the db for every foi event again
=> ⚡️ Fix n+1 queries in request feed generation

froide/foirequest/api_views.py, froide/foirequest/tests/test_api.py
- **⚡️ Prefetch attachment infos in optimize_message_queryset**
- **✅ Add test for FoiMessageSerializer performance**
=> Test for FoiMessageSerializer performacne

froide/foirequest/forms/request.py, froide/foirequest/tests/test_request.py
This breaks leading indentation, e.g.
Please send me the following:
"  1. Document A
2. Document B"
=> 🚸 Do not strip leading / trailing spaces in foirequest body

froide/helper/static/admin/css/inline-actions.css, froide/helper/templates/admin/change_form.html
django cms expects the first .submit-row to be the submit buttons and renders them on the edit modal
=> 🐛 Do not use submit-row class for object admin actions

frontend/styles/variables.scss
Does not affect focus states (i.e. focus ring on buttons).
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/eda7b9fd-a58b-4465-b938-4c7c9bdaec09) | ![image](https://github.com/user-attachments/assets/f1feb8f6-c3b2-4f4e-b5ce-65ccc8a990a3) |
Alternatively, we could set `$enable-shadows` to `false`, which would also alter form elements:
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/e916f213-f90d-404a-b0a8-6032aea3e4c4) | ![image](https://github.com/user-attachments/assets/2edc3266-f5b3-4e6f-8f03-fe80f3e09de3) |
Makes for a more modern, flat look. Fields should probably then have a background color though, since removing the inset shadows would decrease the very little contrast even further.
=> 💄 only show shadow on buttons when focused or active

frontend/styles/variables.scss
the default of `inherit` is more adequate
=> 💄 don't override headings-color-dark, causes issues with utility classes

frontend/javascript/components/redaction/pdf-redaction.vue
Quick fix for #921.
Proper fix would update the whole pdf redaction toolbar for dark mode -- what do you think, reviewers?
=> pdf-redaction: fix bad contrast in dark mode

froide/foirequest/notifications.py, froide/foirequest/tests/test_misc.py, froide/locale/de/LC_MESSAGES/django.po
Closes #567
This is my first attempt at fixing an issue I came across while exploring the project. Please let me know if anything needs adjusting.
=> 🐛 Fix email notifications about updates on requests

README.md, docs/about.rst, pyproject.toml, requirements-test.txt
Hi
I try myself at the froide development setup right now.
While doing this, I try to improve the documentation.
Proposed changes so far:
- changed pyproject.toml classifiers
because they puzzled me
- added ruff as test dependency
because this allows me to avoid a system wide installation of ruff, which is needed for `make test`
- updated readme setup description, based on what the 'Froide CI' Github Job does
because it was outdated and incomplete
- added sections about required system tools and libs
because its tedious to find out one after another
- updated readme 'Update dependencies' using the make target
- removed a version reference from docs/about.rst
it was outdated and it would only get outdated again
`pnpm install` and `pnpm run build` failed at the exifeader postinstall script …
=> Suggested changes based on my setup experience

froide/account/templates/account/includes/breadcrumbs.html, froide/foirequest/templates/foirequest/header/breadcrumb.html, froide/organization/templates/organization/organization_list.html, froide/organization/templates/organization/organization_list_own.html, froide/organization/templates/organization/organization_update_form.html, froide/templates/snippets/breadcrumbs.html, froide/templates/snippets/share_buttons.html
see https://getbootstrap.com/docs/5.3/migration/#helpers-2
Note: `.sr-only` still exists - though it's provided by FontAwesome 4, not Bootstrap.
=> ♻️ replace `.sr-only` with `.visually-hidden`

froide/helper/templates/helper/search/multi_search.html
The search button doesn't have an accessible name. That's because the `aria-hidden="true"`-HTML-attribute is set on the wrong HTML-tag, and should get moved to the preceding icon tag it's most likely meant for (compare to other places in the code like e.g. https://github.com/search?q=repo%3Aokfde%2Ffragdenstaat_de%20fa-search&type=code).
=> fix: search button doesn't have an accessible name

froide/foirequest/templates/foirequest/header/_tags.html, froide/foirequest/templates/foirequest/header/header.html
Extract to include and hide container when no tags and no form. Results in less spacing when not present
=> Improve tag form on request page

frontend/javascript/components/docupload/attachment-icon-preview.vue, frontend/javascript/components/docupload/image-page.vue
because websocket *did* work, got confused by doubled coded and local/staging/prod discrepancies
=> revert postupload failed images preview timing polling

froide/foirequest/models/attachment.py
following up a bug report on the forums, solution discussed with @pajowu
=> remove time limit for deletion of postal message drafts' attachments

frontend/javascript/components/redaction/pdf-redaction.vue
Essentially the infamous last 20% to "mobile-ready pdf redaction" including legacy textOnly mode bugs.
I would appreciate a quick scan of code quality, if possible :)
- clean up "document pixel" vs "device pixel" spaces, respect scaleFactor/renderDensity everywhere, especially in textOnly mode
- this fixes page zoom related padding/margin rounding errors accumulating in Chrom*
- extend padding, relativize line-height calculation the absolute values / magic numbers make even less sense now
- fix weird behaviors, like buttons suddenly submitting, in spite of @click.stop
- fix drag-vs-select behavior in firefox
- better handle right/context clicks
- introduce a debug mode
- add some verbose comments
=> fix pdf redaction w.r.t. page zoom, cross-browser inaccuracies, text mode
